# Generated by Django 5.2.2 on 2025-06-21 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0002_concert_created_at_concert_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="available_for_booking",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="band",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="band",
            name="booking_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="band",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 6, 21, 14, 46, 23, 416192, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="band",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="band_images/"),
        ),
        migrations.AddField(
            model_name="band",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
