# Generated by Django 5.2.2 on 2025-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0003_band_available_for_booking_band_bio_band_booking_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="band_logos/"),
        ),
        migrations.AddField(
            model_name="band",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
