# Generated by Django 5.2.2 on 2025-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0004_band_logo_band_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
